[package]
authors = ["(marshi)masashi yoshikawa <earnest.marshi@gmail.com>"]
name = "rustoid"
version = "0.1.0"
edition = "2018"

[dependencies]
rayon = "1.0.2"
pyo3 = "0.6.0-alpha.2"

[lib]
name = "rustoid"
crate-type = ["cdylib"]
