[package]
authors = ["Messense Lv <messense@icloud.com>"]
name = "word-count"
version = "0.1.0"
edition = "2018"

[dependencies]
rayon = "1.0.2"
pyo3 = "0.6.0-alpha.2"

[lib]
name = "word_count"
crate-type = ["cdylib"]
