[package]
name = "toid"
version = "0.1.0"
authors = ["masashi yoshikawa <yoshikawa@al4.biz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
