[package]
name = "pytoid"
version = "0.1.0"
authors = ["masashi yoshikawa <earnest.marshi@gmail.com>"]
edition = "2018"

[lib]
name = "toid"
crate-type = ["cdylib"]

[dependencies]
rayon = "1.0.2"
pyo3 = "0.8.4"
numpy = "0.7.0"
toid = { path = "../toid" }
